### ISSUE TITLE
Too long path

### ISSUE THREAD

**Issue by gacekssj4** [thirtybees/crossselling#2]
I got error today. Client watched way too many products. Most probably path is too long

UnexpectedValueException::RecursiveDirectoryIterator::__construct(/home/exampleuser/public_html/example.com/cache/smarty/cache/crossselling/shoppingcart/766/842/843/946/855/973/980/988/1205/1162/633/982/804/975/884/1210/1203/1152/1108/1111/1073/1053/1044/1045/1155/1042/856/767/769/787/1018/989/981/846/879/881/911/916/931/940/967/968/969/1/1/3/3/14/ca/97): Failed to open directory: No such file or directory -- 

```php
 $cacheId = 'crossselling|shoppingcart|'.implode('|', $products);

```

Cold be either changed to
```php
 $cacheId = 'crossselling|shoppingcart|'.md5(implode('|', $products));
// or 
$cacheId = 'crossselling|shoppingcart|'.implode('|', array_slice($products,0,4)).'|'.md5(implode('|', $products));
 ```
Or something like this, to shorten path.

**Comment by getdatakick** [comment]
Thank you, I've implemented your suggestion.
